# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6fe57d22536b6a24df37fb318ccb2c1eafbecb018e8848b58c5a6be829a0cf2954c2f9dda2ca11faa72c70ed5b65a1ecdb63479dacc552edcebbdbadc49adc4b

test:
  secret_key_base: 1070f489991aa97714cef6025df93324764860f61b1725fe5623f54109b6c3ac0bcc3ca977b0d47576fee62dcc551ffa0a761b653d0ac1dd50be20582e4c653d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
